---
name: Style
on: push
jobs:
  pylint:
    name: pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install pylint
        run: pip install pylint
      - name: Run pylint
        run: pylint generate.py
  black:
    name: black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install black
        run: pip install black
      - name: Run black
        run: black --diff generate.py
  isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install isort
        run: pip install isort
      - name: Run isort
        run: isort --ensure-newline-before-comments --diff generate.py
